name: Dependencies Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1
      - name: Update Packages
        run: apt update
      - name: Setup Node
        run: |
          apt install npm
          npm install
      - name: Make zip
        run: |
          apt install zip
          zip -r app.zip . -x "*.git*" -x "*.github*" -x "node_modules/.cache/*"
